name: Scheduled Cloudflare Pages Deploy

on:
  schedule:
    # 每天 UTC 时间 00:00 触发
    - cron: '0 0 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  trigger_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 触发 Cloudflare Pages 部署
        run: |
          curl -X POST "${{ secrets.restart }}"
